curl -i http://localhost:8080/login -H "Accept: application/json" -H "Content-Type: application/json" -d '{ "user": "sid1", "password":"pass" }' &
curl -i http://localhost:8080/login -H "Accept: application/json" -H "Content-Type: application/json" -d '{ "user": "sid", "password":"pass" }' &
curl -i http://localhost:8080/login -H "Accept: application/json" -H "Content-Type: application/json" -d '{ "user": "sid1", "password":"pass" }' &
curl -i http://localhost:8080/login -H "Accept: application/json" -H "Content-Type: application/json" -d '{ "user": "sid", "password":"pass" }' & 
curl -i http://localhost:8080/login -H "Accept: application/json" -H "Content-Type: application/json" -d '{ "user": "sid", "password":"pass" }' &
curl -i http://localhost:8080/login -H "Accept: application/json" -H "Content-Type: application/json" -d '{ "user": "sid", "password":"pass" }' &
curl -i http://localhost:8080/login -H "Accept: application/json" -H "Content-Type: application/json" -d '{ "user": "sid1", "password":"pass" }' &
curl -i http://localhost:8080/login -H "Accept: application/json" -H "Content-Type: application/json" -d '{ "user": "sid", "password":"pass" }' &
curl -i http://localhost:8080/login -H "Accept: application/json" -H "Content-Type: application/json" -d '{ "user": "sid", "password":"pass" }' &
curl -i http://localhost:8080/login -H "Accept: application/json" -H "Content-Type: application/json" -d '{ "user": "sid", "password":"pass" }' &
curl -i http://localhost:8080/login -H "Accept: application/json" -H "Content-Type: application/json" -d '{ "user": "sid", "password":"pass" }' &
curl -i http://localhost:8080/login -H "Accept: application/json" -H "Content-Type: application/json" -d '{ "user": "sid", "password":"pass" }' &
curl -i http://localhost:8080/login -H "Accept: application/json" -H "Content-Type: application/json" -d '{ "user": "sid", "password":"pass" }' &
